all:
	g++ src/node_set_based.cpp -Wall -std=c++11 -O3 src/sfmt/SFMT.c -o node_set_based -I /Library/gurobi950/macos_universal2/include -L /Library/gurobi950/macos_universal2/lib -lgurobi_c++ -lgurobi95 -m64
